spring:
  application:
    name: product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: cloud-user
    password: 123456
    url: jdbc:mysql://117.143.62.210:13306/spring-cloud-db?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
